name: simple
description: "Simple CRUD."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  dartz: ^0.10.1
  dio: ^5.9.0
  dropdown_search: ^6.0.2
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_captcha: ^1.0.0
  flutter_secure_storage: ^9.2.4
  get_ip_address: ^0.0.7
  intl: ^0.20.2
  jwt_decoder: ^2.0.1
  meta: ^1.16.0
  universal_html: ^2.2.4
  qr_flutter: ^4.1.0
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  # adaptive_icon_background: "#303F9F"
  # adaptive_icon_foreground: "images/foreground.png"
  # android: true
  # image_path_android: "images/icon-android.png"
  web:
    generate: true
    image_path: "images/pengayoman.png"
    background_color: "#000000"
    theme_color: "#303F9F"

flutter:
  uses-material-design: true
  assets:
    - images/
