name: simple
description: "Simple CRUD."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  dartz: ^0.10.1
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^9.2.2
  get_ip_address: ^0.0.7
  jwt_decoder: ^2.0.1
  intl: ^0.19.0
  meta: ^1.15.0
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  # adaptive_icon_background: "#303F9F"
  # adaptive_icon_foreground: "images/foreground.png"
  # android: true
  # image_path_android: "images/icon-android.png"
  web:
    generate: true
    image_path: "images/pengayoman.png"
    background_color: "#000000"
    theme_color: "#303F9F"

flutter:
  uses-material-design: true
  assets:
    - images/
